version: '3'

services:
  sample-cron:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/sample
    env_file:
      - .env
    restart: on-failure

networks: 
  default: 
    external: 
      name: tracking_default 